### PR TITLE
518 r code samples

### PR DESCRIPTION
**Pull request by skp2140**

### CODE REVIEW

**Comment by alpetric** [comment]
Can you try to fix that space on the right top (wasn't visible before because there was no title bar):

screen shot 2018-02-15 at 17 37 50

**Comment by alpetric** [comment]
Also that one

screen shot 2018-02-15 at 17 41 22

**Comment by skp2140** [comment]
the second comment i corrected, not sure what you mean by the first comment - for me the language bar seems to be aligned:

screen shot 2018-02-16 at 10 22 11 am

**Comment by alpetric** [comment]
screen shot 2018-02-16 at 11 18 57

**Comment by skp2140** [comment]
I fixed the position of the language tab below the top panel

**Comment by alpetric** [comment]
:) I probably should have been more specific. It didn't disturb me that the language tabs where scrolling down along the page, the thing that disturbed me was that there was always a distance between the top of the screen and the language tabs (see my last screenshot)

**Comment by alpetric** [comment]
screen shot 2018-02-16 at 12 11 59

**Comment by alpetric** [comment]
see the red bar in the picture above. this distance was also always there above the language tabs  when scrolling down

**Comment by skp2140** [comment]
i see, as for the starting position, should it be as it is now until you start scrolling? or also placed to the top?

**Comment by alpetric** [comment]
I think it also should be on the top. This will probably solve both problems simultaneously :)

**Comment by skp2140** [comment]
ok, that i have now, 1 more thing, should the selection bar be as thick as the bar above introduction?

**Comment by alpetric** [comment]
Great! much better.

Now one last thing :)

screen shot 2018-02-16 at 13 34 03

**Comment by skp2140** [comment]
changed!

**Pull request merged**
