### PR TITLE
Adds a new slate folder for the hippocampus docs

### PR DESCRIPTION
**Pull request by antonrd**
Basically copy pasted another existing folder, added the content in index.html.md and modified a bit the existing css, specifically in screen.css.scss.

So the main changes are in index.html.md essentially, all the rest is most or less the same as for other projects.

### CODE REVIEW

**Comment by alpetric** [comment]
I deployed it here: https://dev.inpher.io/xor-py

will make a commit to the repo with some slight changes to your PR

**Comment by alpetric** [comment]
you can now:

test locally
```
./test-locally.sh hippocampus
```

or deploy to prod:
```
./deploy.sh -p hippocampus
```

**Comment by skp2140** [comment]
ok, so it seems that to make nokogiri work on ubuntu, one needs to run:

 sudo apt-get install build-essential patch ruby-dev zlib1g-dev liblzma-dev 

prior to installing the gems

**Comment by skp2140** [comment]
Some suggestions:

Introduction
-selects private datasets located on XOR machines -> or datasets located on the analyst machine

Sessions
- maybe we should also mention the * for http_auth as it was used in several examples (until we removed sand)
-descussed in more datails -> discussed in more details


I was thinking maybe more examples for stacking would be helpful as for the rest the user can really just copy/paste our examples, but this is probably enough

I would read through it once more, there are some tiny typos like "logistir regression", " to be passes as an argument", "mismated", etc 

Otherwise, along with the examples this should be sufficient.

**Comment by alpetric** [comment]
I think we can go ahead and merge this. I think how to actually get an API token is outside the scope of this particular document, and customers are instructed during the kickoff how to retrieve an API token

**Comment by skp2140** [comment]
I think it is in good shape and can be merged

**Pull request merged**
